variables:
  SolutionRelativePath: PS.Framework.sln
  - group: FrameworkVersion

trigger:
  branches:
    include:
    - master
    - ci
    - Azure-Test-CI

pr: none
    
pool:
  vmImage: windows-2022

stages:
- stage: Change_Build_Version_Number
  jobs:
  - job: Change Build Version Number
    steps:
     - checkout: none
     - script: echo "Major: $(Major), Minor: $(Minor)"

#- stage: Build_And_Pack
#  jobs:
#  - job: Build
#    timeoutInMinutes: 0
#    displayName: Build
#    steps:
#    - checkout: self
#      path: s
#      target: host
#    - task: DotNetCoreCLI@2
#      displayName: Restore solution
#      inputs:
#        command: restore
#        projects: $(SolutionRelativePath)
#    - task: DotNetCoreCLI@2
#      displayName: Build solution
#      inputs:
#        command: build
#        arguments: -c Release --no-restore
#        projects: $(SolutionRelativePath)
#    - task: PublishBuildArtifacts@1
#      displayName: Publish Artifacts