variables:
- group: FrameworkVersion
- name: SolutionRelativePath
  value: PS.Framework.sln
- name: Revision
  value: $[counter(variables['Minor'], 0)]

trigger:
  branches:
    include:
    - master
    - ci
    - Azure-Test-CI

pr: none

pool:
  vmImage: windows-2022

stages:
- stage: Change_Build_Version_Number
  jobs:
  - job: Change_Build_Version_Number
    variables:
    - name: UpdateUrl
      value: $(System.CollectionUri)$(System.TeamProject)/_apis/distributedtask/variablegroups/1?api-version=5.1-preview.1
    steps:
    - checkout: none
    - powershell: |
        $groupVariables = Invoke-RestMethod -Uri $(UpdateUrl) -Method Get -Headers @{Authorization=("Bearer {0}" -f $(System.AccessToken))}
        $groupVariables.variables.Revision.value = $groupVariables.variables.Revision.value/1 + 1;
        $json = ($groupVariables | ConvertTo-Json -Compress).ToString()
        $pipeline = Invoke-RestMethod -Uri $(UpdateUrl) -Method Put -Body $json -ContentType "application/json" -Headers @{Authorization=("Bearer {0}" -f $(System.AccessToken))}
         
#- stage: Build_And_Pack
#  jobs:
#  - job: Build
#    timeoutInMinutes: 0
#    displayName: Build
#    steps:
#    - checkout: self
#      path: s
#      target: host
#    - task: DotNetCoreCLI@2
#      displayName: Restore solution
#      inputs:
#        command: restore
#        projects: $(SolutionRelativePath)
#    - task: DotNetCoreCLI@2
#      displayName: Build solution
#      inputs:
#        command: build
#        arguments: -c Release --no-restore
#        projects: $(SolutionRelativePath)
#    - task: PublishBuildArtifacts@1
#      displayName: Publish Artifacts