variables:
- group: FrameworkVersion
- name: SolutionRelativePath
  value: PS.Framework.sln
- name: Revision
  value: $[counter(variables['Minor'], 0)]

trigger:
  branches:
    include:
    - master
    - ci
    - Azure-Test-CI

pr: none

pool:
  vmImage: windows-2022

stages:
- stage: Change_Build_Version_Number
  jobs:
  - job: Change_Build_Version_Number
    steps:
     - checkout: none
     - script: |
         #echo '##vso[task.setVariable variable=Revision;]$[counter(variables['Minor'], 0)]'
         #echo 'Version: $(Major).$(Minor).$(Revision)'
         
         variablegroupname=FrameworkVersion
         variablegroupid=1
         
         #use the system.accesstoken on the build agent and a pat token when testing locally.
         bearerToken=$(System.AccessToken)
         header="Authorization: Bearer $bearerToken"
         
         #url="https://dev.azure.com/$adoorg/$adoproj/_apis/distributedtask/variablegroups/$variablegroupid?api-version=5.0-preview.1"
         url2=$(System.CollectionUri)$(System.TeamProject)/_apis/distributedtask/variablegroups/
         echo $url2
         

#- stage: Build_And_Pack
#  jobs:
#  - job: Build
#    timeoutInMinutes: 0
#    displayName: Build
#    steps:
#    - checkout: self
#      path: s
#      target: host
#    - task: DotNetCoreCLI@2
#      displayName: Restore solution
#      inputs:
#        command: restore
#        projects: $(SolutionRelativePath)
#    - task: DotNetCoreCLI@2
#      displayName: Build solution
#      inputs:
#        command: build
#        arguments: -c Release --no-restore
#        projects: $(SolutionRelativePath)
#    - task: PublishBuildArtifacts@1
#      displayName: Publish Artifacts